/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlightsFlightIdRouteImport } from './routes/flights_.$flightId'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsFlightIdRoute = FlightsFlightIdRouteImport.update({
  id: '/flights_/$flightId',
  path: '/flights/$flightId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flights': typeof FlightsRoute
  '/map': typeof MapRoute
  '/flights/$flightId': typeof FlightsFlightIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flights': typeof FlightsRoute
  '/map': typeof MapRoute
  '/flights/$flightId': typeof FlightsFlightIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flights': typeof FlightsRoute
  '/map': typeof MapRoute
  '/flights_/$flightId': typeof FlightsFlightIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flights' | '/map' | '/flights/$flightId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flights' | '/map' | '/flights/$flightId'
  id: '__root__' | '/' | '/flights' | '/map' | '/flights_/$flightId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlightsRoute: typeof FlightsRoute
  MapRoute: typeof MapRoute
  FlightsFlightIdRoute: typeof FlightsFlightIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights_/$flightId': {
      id: '/flights_/$flightId'
      path: '/flights/$flightId'
      fullPath: '/flights/$flightId'
      preLoaderRoute: typeof FlightsFlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlightsRoute: FlightsRoute,
  MapRoute: MapRoute,
  FlightsFlightIdRoute: FlightsFlightIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
